account:
    type:     rest
    resource: @IllarionAccountSystemBundle/Controller/AccountController.php

accountCheck:
    type:     rest
    resource: @IllarionAccountSystemBundle/Controller/AccountCheckController.php

character:
    type:     rest
    resource: @IllarionAccountSystemBundle/Controller/CharacterController.php
