account:
    type:     rest
    resource: @IllarionAccountSystemBundle/Controller/AccountController.php

accountCheck:
    type:     rest
    resource: @IllarionAccountSystemBundle/Controller/AccountCheckController.php
