account:
    type:        rest
    resource:    @IllarionAccountSystemBundle/Controller/AccountController.php
    name_prefix: account_

accountCheck:
    type:        rest
    resource:    @IllarionAccountSystemBundle/Controller/AccountCheckController.php
    name_prefix: account_

character:
    type:        rest
    resource:    @IllarionAccountSystemBundle/Controller/CharacterController.php
    name_prefix: account_
