Illarion\SecurityBundle\Entity\Accounts\Account:
    type: entity
    schema: accounts
    table: account
    repositoryClass: Illarion\SecurityBundle\Entity\Accounts\AccountRepository
    id:
        id:
            type: integer
            id: true
            column: acc_id
            generator:
                strategy: AUTO
    fields:
        accLogin:
            type: string
            length: '50'
            column: acc_login
        accPasswd:
            type: string
            length: '50'
            column: acc_passwd
        accEmail:
            type: string
            length: '50'
            column: acc_email
        accRegisterdate:
            type: datetime
            column: acc_registerdate
        accLastip:
            type: string
            length: '39'
            column: acc_lastip
        accState:
            type: integer
            column: acc_state
        accMaxchars:
            type: integer
            column: acc_maxchars
        accLang:
            type: smallint
            column: acc_lang
    lifecycleCallbacks: {  }
